- hosts: all
  roles:
  - Stouts.deploy
  - Stouts.supervisor
  - Stouts.nginx
  - Stouts.python
  tasks:
    - include: tasks/virtualenv.yml
  handlers:
    - include: handlers/virtualenv.yml
  vars_files:
    - defaults/main.yml
    - .travis.yml
