---

- name: Compile Nginx configuration
  template: src=nginx.conf.j2 dest={{wsgi_nginx_configuration_path}}
  notify:
    - reload nginx

- name: Link nginx config
  file: state=link dest=/etc/nginx/sites-enabled/{{wsgi_project_name}}.conf src={{wsgi_nginx_configuration_path}}
  notify:
    - reload nginx
