---

- name: Setup virtualenv
  shell: virtualenv {{ wsgi_virtualenv }} -p python{{ wsgi_python_version[:3] }}
    creates={{ wsgi_virtualenv }}

- name: Check requirements ({{ wsgi_requirements_path }})
  command: /usr/bin/test -e {{ wsgi_requirements_path }}
  ignore_errors: True
  register: requirements_exists

- name: Install project requirements
  pip: requirements={{ wsgi_requirements_path }} virtualenv={{ wsgi_virtualenv }}
  when: requirements_exists|success
