---
# vim:sw=2:ft=ansible

- name: Setup virtualenv for applications pt. 1
  template:
    dest: "{{item.etc_dir|default('/opt/%s/etc' % item.name)}}/virtualenv.sh"
    group: "{{wsgi_group}}"
    mode: 0755
    owner: "{{wsgi_user}}"
    src: virtualenv.sh
  with_items: "{{wsgi_applications}}"

- name: Setup virtualenv for applications pt. 2
  shell: "{{item.etc_dir|default('/opt/%s/etc' % item.name)}}/virtualenv.sh"
  with_items: "{{wsgi_applications}}"
  changed_when: False
  become_user: "{{wsgi_user}}"
