---
# vim:sw=2:ft=ansible

- name: Setup virtualenv for applications pt. 1
  template: src=virtualenv.sh dest={{wsgi_etc_dir}}/virtualenv.sh mode=0755

- name: Setup virtualenv for applications pt. 2
  shell: "{{wsgi_etc_dir}}/virtualenv.sh"
  changed_when: False
  sudo: yes
  sudo_user: "{{wsgi_user}}"
