---

- name: Setup virtualenv
  shell: virtualenv {{ wsgi_virtualenv }} -p python{{ wsgi_python_version[:3] }}
    creates={{ wsgi_virtualenv }}
  tags: [wsgi, virtualenv]

- pip: name={{item}} virtualenv={{ wsgi_virtualenv }}
  with_items: wsgi_pip_packages 
  tags: [wsgi, virtualenv]

- name: Check requirements ({{ wsgi_requirements_path }})
  command: /usr/bin/test -e {{ wsgi_requirements_path }}
  ignore_errors: yes
  register: requirements_exists
  tags: [wsgi, virtualenv]

- name: Install project requirements
  pip: requirements={{ wsgi_requirements_path }} virtualenv={{ wsgi_virtualenv }}
  when: requirements_exists|success
  tags: [wsgi, virtualenv]

- name: Fix rights for venv directory
  file: name={{ wsgi_virtualenv }} owner={{ base_deploy_user.name }} recurse=yes
  tags: [wsgi, virtualenv]
