---

- name: Setup virtualenv
  shell: virtualenv {{wsgi_virtualenv}} -p {{wsgi_virtualenv_python}}
    creates={{wsgi_virtualenv}}
  when: wsgi_virtualenv != ""
  sudo: yes
  sudo_user: "{{wsgi_user}}"

- set_fact: wsgi_pip=pip
  when: wsgi_virtualenv == ""

- set_fact: wsgi_pip={{wsgi_virtualenv}}/bin/pip
  when: wsgi_virtualenv != ""

- pip: name={{item}} executable={{wsgi_pip}}
  with_items: wsgi_pip_packages 
  sudo: yes
  sudo_user: "{{wsgi_user}}"

- name: Check requirements
  stat: path={{wsgi_requirements}}
  register: wsgi_check

- name: Install project requirements
  pip: requirements={{wsgi_requirements}} executable={{wsgi_pip}}
  when: wsgi_check.stat.exists
  sudo: yes
  sudo_user: "{{wsgi_user}}"
