---

- name: Setup virtualenv
  shell: virtualenv {{wsgi_virtualenv}} -p {{wsgi_virtualenv_python}}
    creates={{wsgi_virtualenv}}
  when: wsgi_virtualenv != ""

- pip: name={{item}} virtualenv={{wsgi_virtualenv}}
  with_items: wsgi_pip_packages 

- name: Check requirements
  stat: path={{wsgi_requirements_path}}
  register: wsgi_requirements

- name: Install project requirements
  pip: requirements={{wsgi_requirements_path}} executable={{wsgi_virtualenv}}/bin/pip
  when: wsgi_requirements.stat.exists

- name: Fix rights for venv directory
  file: name={{wsgi_virtualenv}} owner={{base_deploy_user}} recurse=yes
  when: wsgi_virtualenv != ""
