---

- name: Install additional packages
  apt: name={{item}}
  with_items: wsgi_deb_packages 
  tags: [wsgi]

- include: virtualenv.yml
  tags: [wsgi, virtualenv]

- include: uwsgi.yml
  tags: [wsgi, uwsgi]

- name: Setup Nginx configurations
  template: src=nginx.conf.j2 dest={{wsgi_etc_dir}}/{{item.name}}-nginx.conf owner={{wsgi_user}} group={{wsgi_group}}
  with_items: wsgi_applications
  notify: [ nginx reload ]

- name: Enable nginx sites
  file: state=link dest=/etc/nginx/sites-enabled/{{item.name}}.conf src={{wsgi_etc_dir}}/{{item.name}}-nginx.conf
  with_items: wsgi_applications

- name: Configure log rotation
  template: src=logrotate.conf.j2 dest=/etc/logrotate.d/wsgi.conf
  when: wsgi_log_rotate

# vim:sw=2:ft=ansible
