---

- name: reread supervisor
  shell: /usr/bin/supervisorctl reread && /usr/bin/supervisorctl update

- name: restart uwsgi
  supervisorctl: name=uwsgi-{{ base_project_name }} state=restarted
  ignore_errors: yes

- name: reload nginx
  service: name=nginx state=reloaded
