---
# vim:sw=2:ft=ansible

- name: wsgi restart
  service: name={{item.name}}-uwsgi state=restarted
  with_items: wsgi_applications

- name: wsgi reload
  service: name={{item.name}}-uwsgi state=reloaded
  with_items: wsgi_applications
